In [1]:
import numpy as np

# Pathology INDDID

In [16]:
path_id_TAU = np.array([100551.  , 101068.  , 101105.  , 102149.  , 103032.  , 105000.  ,
       105223.  , 105358.  , 105492.  , 105961.  , 106297.  , 106309.  ,
       106814.  , 106840.  , 107516.  , 107663.  , 107969.  , 108026.  ,
       108077.  , 108196.  , 108508.  , 109115.  , 109176.  , 109299.  ,
       109759.  , 110181.  , 110306.  , 110745.  , 110914.  , 110917.  ,
       111231.  , 111527.  , 111530.  , 112570.  , 113113.  , 113909.  ,
       113938.  , 115001.  , 115592.  , 116504.  , 116591.  , 116607.  ,
       118011.  , 118410.  , 118780.  , 119113.  , 119140.  , 119359.  ,
       119413.  , 120298.  , 122143.  , 101407.  , 101483.  , 103121.  ,
       103782.  , 104281.  , 104937.  , 105564.  , 107187.  , 107429.  ,
       107667.  , 107677.  , 109048.  , 111005.  , 111853.  , 112514.  ,
       112764.  , 114348.  , 114762.  , 114762.02, 115327.  , 116275.  ,
       116401.  , 116409.  , 117566.  , 118575.  ])

path_id_TAU = path_id_TAU.astype(int)

In [17]:
path_id_TDP = np.array([100071.  , 100686.  , 102792.  , 103282.  , 103601.  , 103640.  ,
       103703.  , 103714.  , 104156.  , 104613.  , 104659.  , 104862.  ,
       105247.  , 105686.  , 105769.  , 106335.  , 106461.  , 106641.  ,
       107031.  , 108276.  , 108344.  , 108783.  , 108783.09, 109058.  ,
       109073.  , 109206.  , 109476.  , 110338.  , 110361.  , 110445.  ,
       110581.  , 110658.  , 110705.  , 111077.  , 112202.  , 112273.  ,
       112298.  , 112780.  , 112974.  , 113867.  , 114076.  , 114395.  ,
       114753.  , 116521.  , 116569.  , 116598.  , 116748.  , 117589.  ,
       117630.  , 117637.  , 117663.  , 117753.  , 118190.  , 118234.  ,
       118430.  , 118694.  , 118762.  , 118914.  , 118952.  , 119454.  ,
       119610.  , 119768.  , 120720.  , 120950.  , 121078.  , 121199.  ,
       121261.  , 100096.  , 101045.  , 101272.  , 101525.  , 101778.  ,
       103568.  , 104094.  , 106955.  , 107204.01, 107519.  , 107636.  ,
       108542.  , 108790.  , 108930.  , 109050.  , 109757.  , 111092.  ,
       111517.  , 111612.  , 111862.  , 111863.  , 113227.  , 114978.  ,
       115017.  , 116524.  , 116561.  , 117281.  , 117468.  , 117515.  ,
       117774.  , 118621.  , 118765.  , 118935.  , 119010.  , 119052.  ,
       120814.  ])

path_id_TDP = path_id_TDP.astype(int)

In [6]:
len(path_id_TAU)

76

In [7]:
len(path_id_TDP)

103

# MR INDDID

In [18]:
thick_id_HC = np.array(['100115', '100338', '100387', '100488', '100742', '101080',
       '102187', '102429', '102967', '102974', '103023', '103073',
       '103118', '103824', '104102', '105521', '105601', '106036',
       '106135', '106732', '106897', '107045', '107700', '108014',
       '108560', '108853', '108856', '109075', '109194', '109212',
       '109325', '109346', '109417', '109481', '110342', '111151',
       '111611', '112359', '112916', '113326', '115226', '115311',
       '115629', '116543', '117957', '117964', '118177', '118752',
       '118885', '119158', '119535', '119949', '120506', '124747'])

thick_id_HC = thick_id_HC.astype(int)

In [19]:
thick_id_TAU = np.array(['101483', '104093', '104190', '105564', '106309', '106814',
       '107516', '107677', '108026', '109300', '113113', '115001',
       '116591', '116607', '118064', '118148', '118410', '118780',
       '119089', '120594', '122104', '122375', '122376', '122419',
       '122601', '123352'])

thick_id_TAU = thick_id_TAU.astype(int)

In [20]:
thick_id_TDP = np.array(['101045', '104094', '104862', '105223', '108276', '108344',
       '108790', '109050', '109073', '109476', '112273', '112780',
       '112974', '114753', '115264', '117589', '117637', '118234',
       '118430', '118914', '119349', '119454', '119502', '120141',
       '120691', '120950', '121199', '122821', '124979', '125098'])

thick_id_TDP = thick_id_TDP.astype(int)

In [21]:
len(thick_id_HC)

54

In [22]:
len(thick_id_TAU)

26

In [23]:
len(thick_id_TDP)

30

In [24]:
np.isin(thick_id_HC, path_id_TAU)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [28]:
np.isin(thick_id_HC, path_id_TDP)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [25]:
np.isin(thick_id_TAU, path_id_TAU)

array([ True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
       False, False, False, False, False, False, False, False])

In [31]:
np.isin(thick_id_TAU, path_id_TAU).sum()

13

In [29]:
np.isin(thick_id_TAU, path_id_TDP)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [26]:
np.isin(thick_id_TDP, path_id_TDP)

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False, False, False,  True,  True,
       False, False, False])

In [32]:
np.isin(thick_id_TDP, path_id_TDP).sum()

21

In [30]:
np.isin(thick_id_TDP, path_id_TAU)

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])